# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"


In [32]:
s = "Hi there Sam!"
t = s.split()
print(t)


['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [85]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers. ' . format(planet,diameter))

The diameter of Earth is 12742 kilometers. 


## 3. In this nest dictionary grab the word "hello"

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print d['k1'][3]['tricky'][3]['target'][3]

# Numpy

In [5]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [4]:
array=[0]*10
print(array)


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [5]:
array=[5]*10
print(array)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


## 5. Create an array of all the even integers from 20 to 35

In [6]:
for num in range(20,35,2):
    print(num)

20
22
24
26
28
30
32
34


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [58]:
import numpy as np
a=np.arange(0,9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [78]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate([a,b]))


[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [20]:
import pandas as pd

In [49]:
data = {'Name':['Jai', 'Princi', 'Gaurav'],
        'Qualification':['Msc',  'MCA', 'Phd']}
  
df = pd.DataFrame(data)
  
print(df)

     Name Qualification
0     Jai           Msc
1  Princi           MCA
2  Gaurav           Phd


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [25]:
dates = pd.date_range('2023-01-01', periods=5, freq='D')
s = pd.Series(dates)
print (s)

0   2023-01-01
1   2023-01-02
2   2023-01-03
3   2023-01-04
4   2023-01-05
dtype: datetime64[ns]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [27]:
lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [56]:
df = pd.DataFrame( ['points', 'rebounds']) 
print(df )

          0
0    points
1  rebounds
